global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # BudgetForge API
  # uses the container_name/alias on the shared "budgetforge-backend" network
  - job_name: 'budgetforge-api'
    metrics_path: /metrics
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['budgetforge-api:8080']

  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['budgetforge-postgres-exporter:9187']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['budgetforge-node-exporter:9100']

  # Jenkins metrics (via Prometheus plugin)
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['budgetforge-jenkins:8080']