global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # BudgetForge API metrics
  - job_name: 'budgetforge-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/health'
    scrape_interval: 30s