global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Your BudgetForge API (containerized)
  - job_name: 'budgetforge-api'
    static_configs:
      - targets: ['api:8080']  # Using container name and internal port
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  # PostgreSQL metrics via postgres-exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # System metrics via node-exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  