groups:
- name: postgres
  rules:
  - alert: PostgresDeadlocks
    expr: increase(pg_stat_database_deadlocks[5m]) > 0
    for: 0m
    labels: {severity: warning, service: postgres}
    annotations:
      summary: "Postgres deadlocks detected"
      description: "Deadlocks increased in last 5m."

  - alert: PostgresHighConnections
    expr: pg_stat_activity_count > 100
    for: 5m
    labels: {severity: warning, service: postgres}
    annotations:
      summary: "High number of active connections"
      description: "Active connections > 100."